export const siteConfig = {
  name: 'Kazi Shariful Islam Portfolio',
  author: 'Kazi Shariful Islam',
  title: 'Kazi Shariful Islam Portfolio',
  headline: 'Full Stack Developer & Software Engineer',
  description: 'An elegant, editorial-styled engineering portfolio showcase for Kazi Shariful Islam.',
  url: 'https://kazisharif.dev',
  ogImage: 'https://github.com/kazi331.png',
  twitterHandle: '@kazi331',
  email: 'kazisharif.dev@gmail.com',
  github: 'https://github.com/kazi331',
  linkedin: 'https://linkedin.com/in/kazi331',
  keywords: [
    'Kazi Shariful Islam',
    'Kazi Shariful Islam Portfolio',
    'Full Stack Developer',
    'Software Engineer',
    'Next.js Developer',
    'React Specialist',
    'TypeScript',
    'Node.js',
    'Shopify Functions',
    'Shopify Apps',
    'TanStack Query',
    'Frontend Architecture',
    'Web Development Portfolio',
    'Engineering Blog',
  ],
};
