export interface MobileTechItem {
    id: string;
    name: string;
    category: 'frontend' | 'backend' | 'database' | 'tooling';
    type: 'core' | 'data' | 'learning';
    experience: string;
    level: number;
    description: string;
    relatedProject?: {
        name: string;
        slug?: string;
    };
    color: string;
    accentHex: string;
}

export const mobileTechList: MobileTechItem[] = [
    {
        id: 'javascript',
        name: 'JavaScript',
        category: 'frontend',
        type: 'core',
        experience: '4 yrs exp',
        level: 95,
        description: 'Modern ES6+ syntax, async patterns, event-loop mechanics, closures, and high-performance DOM orchestration.',
        relatedProject: { name: 'EdTech Platform' },
        color: 'rgba(78, 196, 191, 0.9)',
        accentHex: '#4EC4BF',
    },
    {
        id: 'react',
        name: 'React',
        category: 'frontend',
        type: 'core',
        experience: '4 yrs exp',
        level: 94,
        description: 'Component architecture, custom hooks, context management, concurrent rendering, and UI performance profiling.',
        relatedProject: { name: 'Hotelson Flight Booking' },
        color: 'rgba(78, 133, 191, 0.9)',
        accentHex: '#4E85BF',
    },
    {
        id: 'typescript',
        name: 'TypeScript',
        category: 'frontend',
        type: 'core',
        experience: '4 yrs exp',
        level: 92,
        description: 'Compile-time strict type systems, generics, automated schema mapping, and end-to-end full-stack safety.',
        relatedProject: { name: 'EdTech Platform' },
        color: 'rgba(78, 133, 191, 0.9)',
        accentHex: '#4E85BF',
    },
    {
        id: 'nextjs',
        name: 'Next.js',
        category: 'frontend',
        type: 'core',
        experience: '4 yrs exp',
        level: 94,
        description: 'App Router architecture, React Server Components (RSC), dynamic ISR caching, and edge routing.',
        relatedProject: { name: 'Mixory Bundles' },
        color: 'rgba(245, 245, 245, 0.9)',
        accentHex: '#F5F5F5',
    },
    {
        id: 'nodejs',
        name: 'Node.js',
        category: 'backend',
        type: 'core',
        experience: '3 yrs exp',
        level: 93,
        description: 'Event-driven asynchronous services, streaming data pipelines, cluster multi-threading, and REST gateways.',
        relatedProject: { name: 'Mixory Bundles' },
        color: 'rgba(78, 196, 191, 0.9)',
        accentHex: '#4EC4BF',
    },
    {
        id: 'nestjs',
        name: 'NestJS',
        category: 'backend',
        type: 'core',
        experience: '2 yrs exp',
        level: 88,
        description: 'Modular enterprise architecture, dependency injection, execution interceptors, guards, and domain isolation.',
        relatedProject: { name: 'EdTech Platform' },
        color: 'rgba(234, 88, 12, 0.9)',
        accentHex: '#EA580C',
    },
    {
        id: 'postgresql',
        name: 'PostgreSQL',
        category: 'database',
        type: 'data',
        experience: '3 yrs exp',
        level: 90,
        description: 'Relational schema normalization, complex joins, indexing optimization, CTE queries, and ACID transactions.',
        relatedProject: { name: 'Mixory Bundles' },
        color: 'rgba(16, 185, 129, 0.9)',
        accentHex: '#10B981',
    },
    {
        id: 'prisma',
        name: 'Prisma ORM',
        category: 'database',
        type: 'data',
        experience: '2 yrs exp',
        level: 91,
        description: 'Declarative schema modeling, automated migrations, type-safe queries, and database connection pooling.',
        relatedProject: { name: 'Mixory Bundles' },
        color: 'rgba(16, 185, 129, 0.9)',
        accentHex: '#10B981',
    },
    {
        id: 'mongodb',
        name: 'MongoDB',
        category: 'database',
        type: 'data',
        experience: '2 yrs exp',
        level: 89,
        description: 'NoSQL document schema design, aggregation pipelines, document indexing, and cloud Atlas scaling.',
        relatedProject: { name: 'EdTech Platform' },
        color: 'rgba(16, 185, 129, 0.9)',
        accentHex: '#10B981',
    },
    {
        id: 'graphql',
        name: 'GraphQL',
        category: 'tooling',
        type: 'core',
        experience: '2 yrs exp',
        level: 90,
        description: 'Schema-first GraphQL APIs, DataLoader N+1 prevention, custom resolvers, and Shopify Storefront APIs.',
        relatedProject: { name: 'Mixory Bundles' },
        color: 'rgba(139, 92, 246, 0.9)',
        accentHex: '#8B5CF6',
    },
    {
        id: 'react-native',
        name: 'React Native',
        category: 'frontend',
        type: 'core',
        experience: '2 yrs exp',
        level: 86,
        description: 'Cross-platform mobile applications, native modules bridge, push notification flows, and offline sync.',
        relatedProject: { name: 'Maison: The Property App' },
        color: 'rgba(78, 133, 191, 0.9)',
        accentHex: '#4E85BF',
    },
    {
        id: 'shopify',
        name: 'Shopify Functions',
        category: 'tooling',
        type: 'learning',
        experience: '1 yr exp',
        level: 85,
        description: 'WebAssembly-based cart transformations, custom discount logic, and high-conversion embedded merchant apps.',
        relatedProject: { name: 'Mixory Bundles' },
        color: 'rgba(234, 179, 8, 0.9)',
        accentHex: '#EAB308',
    },
    {
        id: 'python',
        name: 'Python',
        category: 'backend',
        type: 'learning',
        experience: '1 yr exp',
        level: 80,
        description: 'Backend automation, data processing pipelines, async workflows, and scripting utility modules.',
        relatedProject: { name: 'Full Stack Web' },
        color: 'rgba(234, 179, 8, 0.9)',
        accentHex: '#EAB308',
    },
    {
        id: 'fastapi',
        name: 'FastAPI',
        category: 'backend',
        type: 'learning',
        experience: '1 yr exp',
        level: 82,
        description: 'Async REST endpoints with Pydantic validation, automatic OpenAPI documentation, and dependency injection.',
        relatedProject: { name: 'Full Stack Web' },
        color: 'rgba(234, 179, 8, 0.9)',
        accentHex: '#EAB308',
    },
    {
        id: 'tailwind',
        name: 'Tailwind CSS',
        category: 'frontend',
        type: 'core',
        experience: '4 yrs exp',
        level: 95,
        description: 'Utility-first responsive layouts, editorial aesthetics, custom design tokens, and fluid animations.',
        relatedProject: { name: 'EdTech Platform' },
        color: 'rgba(56, 189, 248, 0.9)',
        accentHex: '#38BDF8',
    },
    {
        id: 'firebase',
        name: 'Firebase',
        category: 'database',
        type: 'data',
        experience: '2 yrs exp',
        level: 88,
        description: 'Firestore real-time listeners, Firebase Auth, Cloud Messaging (FCM), and cloud function triggers.',
        relatedProject: { name: 'Maison: The Property App' },
        color: 'rgba(245, 158, 11, 0.9)',
        accentHex: '#F59E0B',
    }
];